### PR TITLE
Support passing custom glob-pattern for addtextdomain cli

### PR DESCRIPTION
**Pull request by simison**
This would allow doing this:

```
wpi18n addtextdomain \
    --textdomain=jetpack \
    --glob-pattern='!(docker|node_modules|tests|tools|vendor){*.php,**/*.php}'
```

or:
```
wpi18n addtextdomain \
    --textdomain=jetpack \
    --glob-pattern=*.php
```

### CODE REVIEW

**Comment by bradyvercher** [comment]
This looks good, but can you submit it against the `develop` branch so I can merge it?

**Comment by simison** [comment]
> can you submit it against the develop branch so I can merge it?

Done! Also rebased but via github UI so it left uggly merge commit (just remember to squash, please).

**Comment by bradyvercher** [comment]
Thanks! I'll try to push out a new release with these changes soon.

**Comment by simison** [comment]
Thank you @bradyvercher for quick response to these PRs! Much appreciated. 🙌

I'd have [some use](https://github.com/Automattic/jetpack/pull/9200) for these improvements right away if you'd bake a release. ;-)

**Pull request merged**
